version: '3.18'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: vidalme/willdo-img:v4
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production